spring:
  application:
    name: sunjoy-trm-server-eureka
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /swagger-ui.html   